/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseLayout: typeof import('./src/components/layout/BaseLayout.vue')['default']
    BaseView: typeof import('./src/components/BaseView.vue')['default']
    DateInput: typeof import('./src/components/DateInput.vue')['default']
    DateTimeInput: typeof import('./src/components/DateTimeInput.vue')['default']
    DateTimePicker: typeof import('./src/components/DateTimePicker.vue')['default']
    FloatingActionButton: typeof import('./src/components/FloatingActionButton.vue')['default']
    HomeLayout: typeof import('./src/components/layout/HomeLayout.vue')['default']
    NutAvatar: typeof import('@nutui/nutui')['Avatar']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutColorPicker: typeof import('./src/components/nut/NutColorPicker.vue')['default']
    NutDatePicker: typeof import('@nutui/nutui')['DatePicker']
    NutForm: typeof import('@nutui/nutui')['Form']
    NutFormItem: typeof import('@nutui/nutui')['FormItem']
    NutInput: typeof import('@nutui/nutui')['Input']
    NutInputNumber: typeof import('@nutui/nutui')['InputNumber']
    NutLunarDatePicker: typeof import('./src/components/nut/NutLunarDatePicker.vue')['default']
    NutNavbar: typeof import('@nutui/nutui')['Navbar']
    NutPicker: typeof import('@nutui/nutui')['Picker']
    NutPopup: typeof import('@nutui/nutui')['Popup']
    NutRadio: typeof import('@nutui/nutui')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui')['RadioGroup']
    NutRange: typeof import('@nutui/nutui')['Range']
    NutRecurrentPicker: typeof import('./src/components/NutRecurrentPicker.vue')['default']
    NutSwitch: typeof import('@nutui/nutui')['Switch']
    NutTabbar: typeof import('@nutui/nutui')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmsCodeButton: typeof import('./src/components/form/SmsCodeButton.vue')['default']
  }
}
