/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseView: typeof import('./src/components/BaseView.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutDatePicker: typeof import('@nutui/nutui')['DatePicker']
    NutForm: typeof import('@nutui/nutui')['Form']
    NutFormItem: typeof import('@nutui/nutui')['FormItem']
    NutInput: typeof import('@nutui/nutui')['Input']
    NutNavbar: typeof import('@nutui/nutui')['Navbar']
    NutPopup: typeof import('@nutui/nutui')['Popup']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
