/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseLayout: typeof import('./src/components/layout/BaseLayout.vue')['default']
    BaseView: typeof import('./src/components/BaseView.vue')['default']
    DateInput: typeof import('./src/components/DateInput.vue')['default']
    DateTimeInput: typeof import('./src/components/DateTimeInput.vue')['default']
    DateTimePicker: typeof import('./src/components/DateTimePicker.vue')['default']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    FloatingActionButton: typeof import('./src/components/FloatingActionButton.vue')['default']
    HomeLayout: typeof import('./src/components/layout/HomeLayout.vue')['default']
    NutColorPicker: typeof import('./src/components/nut/NutColorPicker.vue')['default']
    NutLunarDatePicker: typeof import('./src/components/nut/NutLunarDatePicker.vue')['default']
    NutRecurrentPicker: typeof import('./src/components/NutRecurrentPicker.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    RecurrenceFormItem: typeof import('./src/components/form/RecurrenceFormItem.vue')['default']
    ReminderTimeFormItem: typeof import('./src/components/form/ReminderTimeFormItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmsCodeButton: typeof import('./src/components/form/SmsCodeButton.vue')['default']
    SmsFormItem: typeof import('./src/components/form/SmsFormItem.vue')['default']
  }
}
